pipeline:
    build:
        image: python:2.7
        commands:
            - git config --global http.sslverify false
            - chmod +x build.sh
            - ./build.sh
    notify:
        image: drillster/drone-email
        from: redacted
        host: redacted
        port: 25
        recipients:
            - redacted
        skip_verify: true
